"""
AI Finance Analyst — Blueprint 4

Earnings transcript → structured metrics → beat/miss analysis → risk identification.
Human review gate is mandatory — never distribute AI output without analyst sign-off.

Cost: $0.06–0.15 per earnings analysis (Opus synthesis, Haiku extraction).
"""
import json
import os
from dataclasses import dataclass, field
from typing import Optional

import anthropic

client = anthropic.Anthropic(api_key=os.environ.get("AI_API_KEY"))

OPUS   = "claude-opus-4-8"
SONNET = "claude-sonnet-4-6"
HAIKU  = "claude-haiku-4-5-20251001"

DISCLAIMER = (
    "\n\n---\n"
    "⚠️  AI FIRST-PASS ANALYSIS — NOT INVESTMENT ADVICE\n"
    "This analysis was generated by an AI system and has not been verified by a licensed analyst. "
    "All figures must be confirmed against primary sources. Do not distribute or act on this "
    "analysis without qualified professional review and sign-off.\n"
    "---"
)


@dataclass
class EarningsMetrics:
    revenue_actual:       Optional[float] = None   # in millions
    revenue_estimate:     Optional[float] = None
    eps_actual:           Optional[float] = None
    eps_estimate:         Optional[float] = None
    gross_margin:         Optional[float] = None   # percentage
    gross_margin_prior:   Optional[float] = None
    guidance_revenue:     Optional[str]   = None   # raw text
    guidance_eps:         Optional[str]   = None
    key_quotes:           list[str]       = field(default_factory=list)
    data_flags:           list[str]       = field(default_factory=list)   # missing/uncertain figures


@dataclass
class EarningsAnalysis:
    company:              str
    period:               str
    metrics:              EarningsMetrics
    revenue_vs_estimate:  str   # "BEAT" | "MISS" | "IN-LINE" | "UNKNOWN"
    eps_vs_estimate:      str
    gross_margin_trend:   str   # "EXPANDING" | "CONTRACTING" | "STABLE" | "UNKNOWN"
    guidance_assessment:  str
    management_tone:      str   # "CONFIDENT" | "CAUTIOUS" | "MIXED" | "UNCERTAIN"
    primary_risks:        list[str]
    bull_case:            str
    bear_case:            str
    analyst_questions:    list[str]
    confidence:           str   # "HIGH" | "MEDIUM" | "LOW"
    review_required:      bool = True   # always True — never False


def parse_transcript(transcript: str) -> EarningsMetrics:
    """Extract structured metrics from raw earnings transcript."""
    prompt = (
        f"Extract financial metrics from this earnings transcript.\n\n"
        f"TRANSCRIPT:\n{transcript[:6000]}\n\n"
        f"Return JSON with these exact fields (use null for missing values, never estimate):\n"
        f'{{"revenue_actual": null, "revenue_estimate": null, "eps_actual": null, '
        f'"eps_estimate": null, "gross_margin": null, "gross_margin_prior": null, '
        f'"guidance_revenue": null, "guidance_eps": null, '
        f'"key_quotes": [], "data_flags": []}}\n\n'
        f"data_flags: list any figures that are unclear, missing, or ambiguous."
    )
    response = client.messages.create(
        model=SONNET, max_tokens=800,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = response.content[0].text.strip()
    if "```" in raw:
        raw = raw.split("```")[1].lstrip("json").strip()
    try:
        data = json.loads(raw)
        return EarningsMetrics(
            revenue_actual=data.get("revenue_actual"),
            revenue_estimate=data.get("revenue_estimate"),
            eps_actual=data.get("eps_actual"),
            eps_estimate=data.get("eps_estimate"),
            gross_margin=data.get("gross_margin"),
            gross_margin_prior=data.get("gross_margin_prior"),
            guidance_revenue=data.get("guidance_revenue"),
            guidance_eps=data.get("guidance_eps"),
            key_quotes=data.get("key_quotes", []),
            data_flags=data.get("data_flags", []),
        )
    except json.JSONDecodeError:
        return EarningsMetrics(data_flags=["Transcript parsing failed — manual review required"])


def _beat_miss(actual: Optional[float], estimate: Optional[float]) -> str:
    if actual is None or estimate is None:
        return "UNKNOWN"
    diff = (actual - estimate) / estimate
    if diff > 0.01:
        return "BEAT"
    if diff < -0.01:
        return "MISS"
    return "IN-LINE"


def _margin_trend(current: Optional[float], prior: Optional[float]) -> str:
    if current is None or prior is None:
        return "UNKNOWN"
    diff = current - prior
    if diff > 0.5:
        return "EXPANDING"
    if diff < -0.5:
        return "CONTRACTING"
    return "STABLE"


def analyse_earnings(
    company: str, period: str, metrics: EarningsMetrics, transcript: str
) -> EarningsAnalysis:
    """Opus — beat/miss assessment, guidance interpretation, management tone."""
    metrics_summary = (
        f"Revenue: {metrics.revenue_actual}M vs {metrics.revenue_estimate}M estimate\n"
        f"EPS: {metrics.eps_actual} vs {metrics.eps_estimate} estimate\n"
        f"Gross margin: {metrics.gross_margin}% (prior: {metrics.gross_margin_prior}%)\n"
        f"Guidance revenue: {metrics.guidance_revenue}\n"
        f"Guidance EPS: {metrics.guidance_eps}\n"
        f"Key quotes: {'; '.join(metrics.key_quotes[:3])}\n"
        f"Data flags: {'; '.join(metrics.data_flags) or 'None'}"
    )

    prompt = (
        f"Analyse earnings for {company} ({period}). You are a buy-side equity analyst producing a first-pass.\n\n"
        f"METRICS:\n{metrics_summary}\n\n"
        f"TRANSCRIPT EXCERPT:\n{transcript[:3000]}\n\n"
        f"Assess:\n"
        f"1. GUIDANCE_ASSESSMENT: interpret guidance vs prior expectations (2–3 sentences)\n"
        f"2. MANAGEMENT_TONE: CONFIDENT | CAUTIOUS | MIXED | UNCERTAIN — with brief justification\n"
        f"3. PRIMARY_RISKS: 3 specific risks from this report (not generic sector risks)\n"
        f"4. BULL_CASE: 2–3 sentence bull thesis grounded in this quarter's data\n"
        f"5. BEAR_CASE: 2–3 sentence bear thesis grounded in this quarter's data\n"
        f"6. ANALYST_QUESTIONS: 4 specific questions for the Q&A based on this report\n"
        f"7. CONFIDENCE: HIGH | MEDIUM | LOW — based on data quality and clarity\n\n"
        f"Flag uncertain figures with [UNVERIFIED]. Never interpolate missing data."
    )
    response = client.messages.create(
        model=OPUS, max_tokens=1500,
        system="You are a buy-side equity analyst. This is first-pass analysis only.",
        messages=[{"role": "user", "content": prompt}],
    )
    return _parse_analysis(response.content[0].text, company, period, metrics)


def _parse_analysis(text: str, company: str, period: str, metrics: EarningsMetrics) -> EarningsAnalysis:
    data: dict = {
        "guidance": "", "tone": "MIXED", "risks": [], "bull": "", "bear": "",
        "questions": [], "confidence": "MEDIUM",
    }
    current_key = None
    buffer: list[str] = []

    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("GUIDANCE_ASSESSMENT:"):
            data["guidance"] = stripped.split(":", 1)[1].strip(); current_key = None
        elif stripped.startswith("MANAGEMENT_TONE:"):
            raw_tone = stripped.split(":", 1)[1].strip().split()[0].upper()
            data["tone"] = raw_tone if raw_tone in ("CONFIDENT","CAUTIOUS","MIXED","UNCERTAIN") else "MIXED"
            current_key = None
        elif stripped.startswith("PRIMARY_RISKS:"):
            current_key = "risks"; buffer = []
        elif stripped.startswith("BULL_CASE:"):
            if current_key: _flush(data, current_key, buffer); buffer = []
            data["bull"] = stripped.split(":", 1)[1].strip(); current_key = None
        elif stripped.startswith("BEAR_CASE:"):
            data["bear"] = stripped.split(":", 1)[1].strip(); current_key = None
        elif stripped.startswith("ANALYST_QUESTIONS:"):
            current_key = "questions"; buffer = []
        elif stripped.startswith("CONFIDENCE:"):
            if current_key: _flush(data, current_key, buffer); buffer = []
            raw_conf = stripped.split(":", 1)[1].strip().split()[0].upper()
            data["confidence"] = raw_conf if raw_conf in ("HIGH","MEDIUM","LOW") else "MEDIUM"
            current_key = None
        elif stripped.startswith(("- ", "• ", "1.", "2.", "3.", "4.")) and current_key:
            item = stripped.lstrip("-•1234567890. ").strip()
            if item: buffer.append(item)
        elif stripped and current_key == "questions":
            buffer.append(stripped)

    if current_key: _flush(data, current_key, buffer)

    return EarningsAnalysis(
        company=company, period=period, metrics=metrics,
        revenue_vs_estimate=_beat_miss(metrics.revenue_actual, metrics.revenue_estimate),
        eps_vs_estimate=_beat_miss(metrics.eps_actual, metrics.eps_estimate),
        gross_margin_trend=_margin_trend(metrics.gross_margin, metrics.gross_margin_prior),
        guidance_assessment=data["guidance"],
        management_tone=data["tone"],
        primary_risks=data["risks"][:3],
        bull_case=data["bull"],
        bear_case=data["bear"],
        analyst_questions=data["questions"][:4],
        confidence=data["confidence"],
    )


def _flush(data: dict, key: str, buf: list) -> None:
    if buf: data[key] = buf[:]


def analyse_earnings_from_transcript(
    company: str, period: str, transcript: str, estimates: Optional[dict] = None
) -> str:
    """
    Full pipeline. Returns formatted analysis string with mandatory disclaimer.
    estimates: optional dict with keys revenue_estimate, eps_estimate (floats).
    """
    metrics = parse_transcript(transcript)
    if estimates:
        metrics.revenue_estimate = estimates.get("revenue_estimate", metrics.revenue_estimate)
        metrics.eps_estimate     = estimates.get("eps_estimate", metrics.eps_estimate)

    analysis = analyse_earnings(company, period, metrics, transcript)

    lines = [
        f"EARNINGS ANALYSIS: {analysis.company} — {analysis.period}",
        "=" * 60,
        f"Revenue:       {analysis.revenue_vs_estimate}",
        f"EPS:           {analysis.eps_vs_estimate}",
        f"Gross margin:  {analysis.gross_margin_trend}",
        f"Mgmt tone:     {analysis.management_tone}",
        f"Confidence:    {analysis.confidence}",
        "",
        f"GUIDANCE\n{analysis.guidance_assessment}",
        "",
        "PRIMARY RISKS",
        *[f"  • {r}" for r in analysis.primary_risks],
        "",
        f"BULL CASE\n{analysis.bull_case}",
        "",
        f"BEAR CASE\n{analysis.bear_case}",
        "",
        "ANALYST QUESTIONS FOR Q&A",
        *[f"  {i+1}. {q}" for i, q in enumerate(analysis.analyst_questions)],
    ]
    if analysis.metrics.data_flags:
        lines += ["", "DATA FLAGS (verify before distributing)"]
        lines += [f"  ⚠ {f}" for f in analysis.metrics.data_flags]

    return "\n".join(lines) + DISCLAIMER


if __name__ == "__main__":
    sample_transcript = """
    Good afternoon and welcome to Acme Corp's Q3 2025 earnings call.

    We're pleased to report Q3 revenue of $142.3 million, representing 18% year-over-year growth.
    This compares to analyst consensus of $138.5 million.

    Non-GAAP EPS came in at $0.87, versus the consensus estimate of $0.82.

    Gross margin expanded to 68.2% from 65.1% in Q3 2024, driven by improved infrastructure efficiency
    and a favorable shift in product mix toward our higher-margin enterprise tier.

    For Q4, we're guiding to revenue of $148-152 million, which is slightly above the current
    consensus of $147 million. We expect non-GAAP EPS of $0.88-0.92.

    I want to highlight that while we're seeing strong momentum in enterprise, our SMB segment
    saw some softness this quarter with net revenue retention dipping to 108% from 114%.
    We believe this reflects macro pressure on smaller businesses rather than competitive dynamics,
    but we're monitoring it closely.
    """

    estimates = {"revenue_estimate": 138.5, "eps_estimate": 0.82}
    result    = analyse_earnings_from_transcript("Acme Corp", "Q3 2025", sample_transcript, estimates)
    print(result)
